[package]
name = "fixture"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
anyhow = "*"
arch = { path = "../../arch" }
base = "*"
crc32fast = "1.3"
cfg-if = "*"
libc = "0.2.65"
rand = "0.8"
tempfile = "3"
prebuilts = { path = "../../prebuilts" }
log = "*"
shlex = "1.3"
url = "2.3"
delegate = {path = "../guest_under_test/rootfs/delegate"}
serde = {version = "*", features = ["derive"]}
serde_json = "*"
