[package]
name = "libva"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
anyhow = "*"
bitflags = "1"
base = { path = "../../base" }
crc32fast = "1.2.1"

[build-dependencies]
pkg-config = "*"
