[package]
name = "bit_field_derive"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
proc-macro2 = "^1"
quote = "^1"
syn = "^1"

[lib]
proc-macro = true
path = "bit_field_derive.rs"
