[book]
authors = ["The ChromiumOS Authors"]
language = "en"
multilingual = false
src = "src"
title = "Book of crosvm"

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]
[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

# Redirect previously used paths to updated locations.
[output.html.redirect]
"building_crosvm/chromiumos.html" = "../integration/chromeos.html"

[output.linkcheck]
