[package]
name = "plugin_proto"
version = "0.17.0"
authors = ["The Chromium OS Authors"]
build = "build.rs"

[dependencies]
protobuf = "*"
kvm_sys = { path = "../kvm_sys" }

[build-dependencies]
cc = "=1.0.25"
protoc-rust = "=1.4.3"
