[package]
name = "vhost_user_devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[features]
net = ["data_model", "net_util", "virtio_sys"]
wl = ["devices/minigbm"]
block = ["data_model", "disk"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "vhost-user-net-device"
path = "src/net.rs"
required-features = ["net"]

[[bin]]
name = "vhost-user-wl-device"
path = "src/wl.rs"

[[bin]]
name = "vhost-user-block-device"
path = "src/block.rs"
required-features = ["block"]

[dependencies]
anyhow = "*"
base = { path = "../base" }
cros_async = { path = "../cros_async" }
data_model = { path = "../data_model", optional = true }
devices = { path = "../devices" }
disk = { path = "../disk", optional = true}
getopts = { version = "0.2" }
libc = "*"
net_util = { path = "../net_util", optional = true }
once_cell = "1.7.2"
remain = "*"
sync = { path = "../sync" }
sys_util = { path = "../sys_util" }
thiserror = "*"
virtio_sys = { path = "../virtio_sys", optional = true }
vm_memory = { path = "../vm_memory" }
vmm_vhost = { version = "*", features = ["vhost-user-slave"] }

[dependencies.futures]
version = "*"
default-features = false

[dev-dependencies]
data_model = { path = "../data_model" }
tempfile = { path = "../tempfile" }
