[package]
name = "audio_streams_conformance_test"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[[bin]]
name = "audio_streams_conformance_test"
path = "src/main.rs"

[features]
audio_cras = ["dep:libcras"]
chromeos = ["audio_cras"]

[dependencies]
argh = "*"
audio_streams = "*"
cfg-if = "1.0.0"
cros_async = { path = "../../cros_async" } # provided by ebuild
num = "*"
libcras = { version = "*", optional = true  }
remain = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
thiserror = "1.0.20"

[target.'cfg(unix)'.dependencies]
minijail = "*" # provided by ebuild

[patch.crates-io]
audio_streams = { path = "../../common/audio_streams"}  # ignored by ebuild
libcras = { path = "../../libcras_stub" } # ignored by ebuild
minijail = { path = "../../third_party/minijail/rust/minijail" } # ignored by ebuild
