[package]
name = "cros_tracing_analyser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "*"
libtracecmd = ">=0.2.0"
once_cell = "1.18.0"
serde = { version = "*", features = ["derive"] }
serde_json = "*"

[workspace]
