[package]
name = "cros_tracing_analyser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
argh = "0.1"
libtracecmd = "0.2"
log = "0.4"
once_cell = "1.18.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[workspace]
