[package]
name = "data_model"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
static_assertions = "1.1"
cfg-if = "1.0.0"
libc = "*"
remain = "0.2"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.20"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["everything", "std", "impl-default"] }

[target.'cfg(unix)'.dependencies]
libc = "*"


