[package]
name = "data_model"
version = "0.1.1-alpha.1"
authors = ["The Chromium OS Authors"]
edition = "2021"
include = ["src/**/*", "Cargo.toml", "LICENSE"]
description = "[highly unstable] data model for virtualization"
license-file = "LICENSE"

[dependencies]
static_assertions = "1.1"
serde = { version = "1", features = ["derive"] }
zerocopy = { version = "0.7", features = ["derive"] }
