[package]
name = "resources"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[features]
wl-dmabuf = ["gpu_buffer"]

[dependencies]
gpu_buffer = { path = "../gpu_buffer", optional = true }
libc = "*"
sys_util = { path = "../sys_util" }
msg_socket = { path = "../msg_socket" }
