[package]
name = "resources"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
libc = "0.2"
base = { path = "../base" }
serde = { version = "1", features = ["derive"] }
remain = "0.2"
thiserror = "1"
