[package]
name = "anti_tamper"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
anti-tamper = []
kiwi = []

[dependencies]
base = { path = "../base" }
