[package]
name = "kernel_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
data_model = { path = "../common/data_model" }
libc = "*"
base = { path = "../base" }
remain = "*"
resources = { path = "../resources" }
thiserror = "*"
vm_memory = { path = "../vm_memory" }
zerocopy = "*"

[dev-dependencies]
tempfile = "3"
