[package]
name = "perfetto"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
# Bypassing default features requires specifying either openssl or
# pure-rust-hashes.
default = ["openssl"]

# Use a pure Rust crate for hashing instead of openssl.
pure-rust-hashes = ["sha2"]

[dependencies]
anyhow = "1"
base = { path = "../base" }
cfg-if = "1.0.0"
cros_tracing_types = { path = "../cros_tracing_types" }
openssl = { version = "0.10", optional = true }
protobuf = "3.2"
serde = { version = "1", features = [ "derive" ] }
sha2 = { version = "0.10", optional = true }
sync = { path = "../common/sync" }
zerocopy = { version = "0.7", features = ["derive"] }

[build-dependencies]
proto_build_tools = { path = "../proto_build_tools" }
