[package]
name = "integration_tests"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dev-dependencies]
anyhow = "*"
arch = { path = "../arch" }
base = "*"
cfg-if = "*"
libc = "0.2.65"
prebuilts = { path = "../prebuilts" }
tempfile = "3"

[features]
direct = []
