[package]
name = "system_api"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[lib]
path = "src/system_api.rs"

[target.'cfg(unix)'.dependencies]
dbus = "0.9"
protobuf = "2.24"
