[package]
name = "vcpu_blocker_analyzer_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
argh = "0.1"
env_logger = "0.10"
log = "0.4"
regex = "1.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1"

[dev-dependencies]
rstest = "0.19"


[workspace]
