[package]
name = "sys_util"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
data_model = { path = "../data_model" } # provided by ebuild
libc = "*"
poll_token_derive = { version = "*", path = "poll_token_derive" }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
sync = { path = "../sync" } # provided by ebuild
tempfile = { path = "../tempfile" } # provided by ebuild

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.2"

[features]
chromeos = []

[workspace]
