[package]
name = "fuse"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
base = "*"
bitflags = "1"
data_model = "*"
enumn = { path = "../enumn" }
libc = "*"
thiserror = "1.0.20"