[package]
name = "qcow"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[lib]
path = "src/qcow.rs"

[dependencies]
byteorder = "*"
libc = "*"

[dev-dependencies]
sys_util = { path = "../sys_util" }
